### ISSUE TITLE
Unreadable alternate column in night mode

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__BetterSearch#1]
![image](https://user-images.githubusercontent.com/13769570/72219978-dfad9f00-3543-11ea-9e90-932ddf86eb43.png)
Hello. The alternate column is unreadable in night mode.

**Comment by ijgnd** [comment]
thanks for the report. I just uploaded a new version to Ankiweb that should work with the latest "Night Mode" version from 2020-01-13. I also added some other functions which means I might have introduced some bug ... Could you test it and let me know if you notice a problem?

**Comment by ghost** [comment]
Seems to work perfectly.
Just one thing, could you add hierarchical tag support? When I search say #Medicine::Step_Decks::Zanki::Hematology_&_Oncology", I want all the cards tagged under that umberella. So #Medicine::Step_Decks::Zanki::Hematology_&_Oncology*" would fit the criteria better.

**Comment by ijgnd** [comment]
I like this idea. Could you update and try the latest version. Any other good ideas for this add-on?

**Comment by ghost** [comment]
It works great. Thank you so much. I don't have any off the top of my head but I'll be sure to open up an issue if I do.
