### ISSUE TITLE
Searching has an issue with a changes in upper/lower case.

### ISSUE THREAD

**Issue by PaulKnauseder** [ijgnd/anki__BetterSearch#10]
Hello,
i really like this addon and i thought that you could improve it by ignoring upper/lower case. 

In the dialog window of the addon I can either find a tag if I spell it all correctly (no surprise) or if I type it all in lowercase. Anything in between doesn't work.
Without the addon it doesn't matter if i mix upper and lowe case.

e.g. the tag I am looking for is 'PM_III::Biochemistry'. (the III are 3 iii)

tag:"PM_III::Biochemistry" works
tag:"pm_iii::biochemistry" works
tag:"PM_III::biochemistry" doesn't work
tag:"pm_iii::Biochemistry" doesn't work

If it's not too much work I think this would be a nice improvement.
Thanks for your work!

**Comment by ijgnd** [comment]
Good idea. I just included this in the most recent version.

Before I upload this to ankiweb this needs some testing.

You can download the most recent version from here: https://github.com/ijgnd/anki__browser_search__quick_insert_tag_deck_notetype/releases/download/0.06/anki__browser_search__quick_insert_tag_deck_notetype__2020-05-06.ankiaddon

For installing ankiaddon files see: 
- for macos: https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation-macos.gif
- general: https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif

**Comment by ijgnd** [comment]
your feature is *disabled* by default. you need to enable it in the config.

**Comment by PaulKnauseder** [comment]
Just enabled it. Thanks for updating.
