### ISSUE TITLE
[Feature request] Adding cards/editing

### ISSUE THREAD

**Issue by PaulKnauseder** [ijgnd/anki__BetterSearch#11]
Hello,
this addon adds a lot of convenience to searching in the browser. Have you thought about expanding it to the "add cards"-window or the editor? 
If it's not too much work, that would be a great way of improving the addon imo.

**Comment by ijgnd** [comment]
My add-on [Extended Tag Add/Edit Dialog](https://ankiweb.net/shared/info/1135507717) has the filter dialog to insert tags in the editor. The default shortcut is "Alt+Shift+5" - but you can adjust it to something easier to press in the config.

I'll update the description of the add-on to point to the other add-on.

Does this solve your problem?

**Comment by PaulKnauseder** [comment]
Absolutely! Thats exactly what i was looking for. Thank you!
