### ISSUE TITLE
Text Search

### ISSUE THREAD

**Issue by fUpDWfYS** [ijgnd/anki__BetterSearch#21]
Hello! The new search functions built into Anki seem to be interfering with the defined search terms that BetterSearch builds.

For example when you create a search term using "dnf:" BetterSearch will create a term like this:
`(note:Cloze-AnKingMaster-v2 "Text:*GnRH*")`

However when you press Enter to search Anki will re-write it as:
`AND ("note:Cloze-AnKingMaster-v2" AND "Text:*GnRH*")`

**Comment by ijgnd** [comment]
Thanks for this report.

I'm still waiting because it seems as if this search rewriting feature might be removed again, see [this post by the anki creator form 2020-04-03](https://forums.ankiweb.net/t/would-it-be-possible-to-toggle-off-the-new-browser-tendency-to-add-operators-and-quotes/8948/3).

**Comment by ijgnd** [comment]
the rewriting feature was removed so this should no longer occur. So I close this bug.

If you still run into this problem reopen this bug and let me know.
