### ISSUE TITLE
2.1.45 Alpha 1-> add-on broken

### ISSUE THREAD

**Issue by NamelessGO** [ijgnd/anki__BetterSearch#23]
![image](https://user-images.githubusercontent.com/66227691/118549829-f9f42000-b729-11eb-8643-3e5b88958f48.png)
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

**Comment by ijgnd** [comment]
thanks for letting me know. I just uploaded a new version to ankiweb that should fix this problem. Could you update and try again.

I expect that .45 will break other functions of this add-on and also many other add-ons of mine. Please let me know about errors you find.

**Comment by ijgnd** [comment]
should be fixed with version from 2021-07-10.
