### ISSUE TITLE
Put quotes around tag searches

### ISSUE THREAD

**Issue by ryerrabelli** [ijgnd/anki__BetterSearch#24]
For example, one of the AnKing tags is *#AK_Step1_v8::#FirstAid::01_Biochem::06_Metabolism::14_TCA_cycle_(Krebs_cycle)*  

If you search for that using the dialog, it searches:  
`tag:#AK_Step1_v8::#FirstAid::01_Biochem::06_Metabolism::14_TCA_cycle_(Krebs_cycle)*`  
And searching that gives the error:  
**"Invalid search - please check for typing mistakes."**

However, the search below works:  
`tag:"#AK_Step1_v8::#FirstAid::01_Biochem::06_Metabolism::14_TCA_cycle_(Krebs_cycle)*"`  

I made this fix in my local code by changing line 201 in **onTextChange.py** 
`"surround_with_quotes": False,`
becomes  
`"surround_with_quotes": True,`

Below is the full context for reference:   
```
    if before[-4:] == "tag:" and gc("modify_tag"):
        vals = {
            "remove_from_end_of_before": 0,
            "insert_space_at_pos_in_before": -4,
            "dict_for_dialog": False,
            "vals": tags(col),
            "surround_with_quotes": True,
            "infotext": False,
            "windowtitle": "Anki: Select tag to search",
            "show_prepend_minus_button": True,
            "show_star": True,
            "check_star": gc("tag insertion - add '*' to matches"),
        }
```

**Comment by ijgnd** [comment]
thanks

merged with https://github.com/ijgnd/anki__BetterSearch/pull/25 

note to myself: related commits:  

2754ffa (2023-06-12) quote all tags
03a2eae (2023-06-15) remove all tag quoting
2754ffa (2024-02-18) reintroduce some tag quoting
