### ISSUE TITLE
No option available for shortcut to date edited dialog

### ISSUE THREAD

**Issue by dochypermoose** [ijgnd/anki__BetterSearch#28]
As title says, there's not option to create a shortcut for the date edited dialog and when I manually add it, nothing happens. 

Also, might want to change key binding away from starting with CTRL+H since that's (CMD+H) the native "hide window" shortcut for every Mac ever and you need to be very specific to get this working in most instances.

**Comment by ijgnd** [comment]
thanks for report. sorry for the late reply.

Both were good ideas:

- I changed the default shortcut in 2023-06, see https://github.com/ijgnd/anki__BetterSearch/commit/924aca61a98edd221e36a8829742c78134a124c6
- shortcuts for date/edited added in 2023-06, see 52e8a6f
