### ISSUE TITLE
Tag exclusion bug

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__BetterSearch#3]
Hello.
When trying to exclude tag, the addon inserts a space between the "-" and the inserted tag

**Comment by ijgnd** [comment]
thanks for the report.

Could you try the latest version from ankiweb? This version should fix this.

I added another feature: when you open the dialog with a shortcut and then press "alt" while closing it a minus is inserted infront of what's inserted. So you should be able to quickly exclude.

**Comment by ghost** [comment]
Works perfectly. Thank you.
