### ISSUE TITLE
Add tag:none option

### ISSUE THREAD

**Issue by ghost** [ijgnd/anki__BetterSearch#5]
Hello. 
To find cards with no tags, a none option in the filter bar would be appreciated.

**Comment by ijgnd** [comment]
at the moment to search for `tag:none` i type: `t a g : ESC n o n e RETURN`. Doesn't this work for you?

But adding none to the filter dialog would probably be better. Added to my Todo list as low priority at the moment.

**Comment by ghost** [comment]
That works. Thank you.
