### ISSUE TITLE
Error when opening browser on 2.1.22

### ISSUE THREAD

**Issue by AnKingMed** [ijgnd/anki__BetterSearch#6]
![image](https://user-images.githubusercontent.com/57678116/76323352-39afb400-62aa-11ea-9d1a-0977baec8847.png)

This is the error I'm getting (advanced browser is toggled off)

**Comment by ijgnd** [comment]
Thanks for the report.

But could you try again? This looks very much like a problem with advanced browser to me:

Advanced browser instantiates the class CardStats [here: cs = CardStats(None, None)](https://github.com/hssm/advanced-browser/blob/cc6103512d9d093379a215a1dccc3c164cdf3114/advancedbrowser/advancedbrowser/custom_fields.py#L30). So the arguments are "None, None".

But CardStats from anki.py wants these arguments: `def __init__(self, col: anki.storage._Collection, card: anki.cards.Card)`, see [here](https://github.com/ankitects/anki/blob/131d37dca52c29033432e0149052093ab1c79461/pylib/anki/stats.py#L27). So `CardStats.__init__.py` assumes that self.col is not a None type but a collection object which explains the error line 28.

**Comment by AnKingMed** [comment]
I deleted the advanced browser add-on rather than toggling and it seems to have resolved this. Must be only an issue with Advanced Browser. Sorry about that.

**Comment by ijgnd** [comment]
I forgot: Thanks. Better one report (that includes all the details like yours) too many than one to few.
